### ISSUE TITLE
Make this a proper service

### ISSUE THREAD

**Issue by riordan** [whosonfirst/py-mapzen-whosonfirst-search#9]
It would be great to be able to hit a service with a WoF ID, and then get back the ID's for all its children.

Ideally this could be faceted by type (e.g. retrieve all the county record IDs for the United States) and responses would be separated by type.

**Comment by thisisaaronland** [comment]
Adding @heffergm 

"This" is just a bog standard ES setup with a lot of pre-processing of keys into sane types to prevent ES from trying to get clever (and making everything sad).

A general purpose "faceting" endpoint for WOF would be useful, I agree, but that's just ES. There is nothing specific about this package to the functionality. I guess the questions are: Is this an internal-only thing; is it an API thing; does it need caching (probably); How does cache-invalidation happen?

If we're just fronting/caching the queries on ES then there are many ways/places to do it.
